version: '3.8'

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: tanryberdi
      POSTGRES_PASSWORD: tanryberdi
    ports:
        - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "50051:50051"
    depends_on:
      - db

volumes:
    postgres_data: