services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: tanryberdi
      POSTGRES_PASSWORD: tanryberdi
    ports:
        - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "50051:50051"
    depends_on:
      - db

volumes:
    postgres_data: